---
#
- name: config_cron | Configure sync time crontab
  cron:
    name: sync_time
    minute: "0"
    hour: "*/2"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/sbin/ntpdate {{ ntpserver }} &>/dev/null"


- name: config_cron | Configure ansible server get fact
  cron:
    name: get_fact
    minute: "0"
    hour: "2"
    job: "/usr/bin/ansible all -m setup &>/dev/null"
  when: ansible_local.customize.private.role == "ansible_server"