---

- name: check | 检查代码是否存在
  shell: "ls {{ deploy_file }}"
  connection: local
  register: deploy_file_result
  changed_when: false

- name: check | 工作目录如果不存在则创建
  file: "path={{ deploy_service_workpath }} owner={{ deploy_service_user }} state=directory"

- name: check | 代码存储目录如果不存在则创建
  file: "path={{ item }} state=directory"
  with_items:
    - "{{ online_code_path }}"
    - "{{ previous_code_path }}"
    - "{{ history_code_path }}"
    - "{{ deploy_service_workpath }}"

- name: check | rsync客户端如果不存在则创建
  yum: name=rsync
