---

- name: deploy | 清空代码更新目录
  file: "path={{ online_code_path }} state=absent"

- name: deploy | 代码更新目录如果不存在则创建
  file: "path={{ online_code_path }} state=directory"

- name: deploy | 拷贝代码到目标服务器
  unarchive:
    src: "{{ deploy_file_result.stdout_lines[0] }}"
    dest: "{{ online_code_path }}"

- name: deploy | 备份线上代码
  synchronize:
    src: "{{ deploy_service_workpath }}"
    dest: "{{ previous_code_path }}/{{ deploy_project }}"
    delete: yes
    checksum: yes
    rsync_opts:
      - "--no-motd"
      - "--exclude=.svn"
  delegate_to: "{{ inventory_hostname }}"

- name: deploy | 同步最新代码
  synchronize:
    src: "{{ online_code_path }}/"
    dest: "{{ deploy_service_workpath }}"
    delete: yes
    checksum: yes
    rsync_opts:
      - "--no-motd"
      - "--exclude=.svn"
    delegate_to: "{{ inventory_hostname }}"

- name: deploy | 目录授权给{{ deploy_service_user }}
  file: "path={{ deploy_service_workpath }} owner={{ deploy_service_user }} group={{ deploy_service_user }} recurse=yes"

