---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: Configure host ssh key authentication
      authorized_key:
        user: root
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        state: present

