---
#
- name: config_repe |copy repo file
  template:
    src: "{{ item }}.j2"
    dest: "/etc/yum.repos.d/{{ item }}"
  with_items:
    - "CentOS-ALiYun-Base.repo"
    - "private-cong.repo"
  notify: yum makecache

