#
- name: system_optimization | Change nofile limits.
  lineinfile: dest=/etc/security/limits.conf line={{ item }}
  with_items:
    - '* - nofile 165535'
    - '* soft nofile 165535'
    - '* hard nofile 165535'
    - '* soft memlock unlimited'
    - '* hard memlock unlimited'
  tags: config_nofile_limits

- name: system_optimization | copy config sysctl file
  copy:
    src: "sysctl.conf"
    dest: "/etc/sysctl.conf"
    backup: yes
  tags: config_sysctl_file
  notify: load sysctl config

- name: system_optimization | Disable SELinux
  selinux:
    state: disabled
