---
#
- name: configure | 配置nginx.conf
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file }}"
    mode: 0644
  notify: reload nginx


- name: configure | 创建虚拟主机配置目录
  file:
    path: "{{ nginx_vhost_path }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0755


- name: configure | 拷贝默认主机配置文件
  template:
    src: default_server.conf.j2
    dest: "{{ nginx_vhost_path }}/default_server.conf"
    mode: 0644
  notify: reload nginx
  when: default_server_name is defined


- name: configure | 拷贝nginx脚本
  template:
    src: nginx.sh.j2
    dest: /etc/init.d/nginx
    mode: 0755


- name: configure | Append nginx services
  shell: "chkconfig --add nginx && chkconfig nginx on"


- name: configure | Ensure nginx is running for centos 6
  service: "name=nginx state=started enabled=yes"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"


- name: configure | Ensure nginx is running for centos 7
  service: "name=nginx state=started enabled=yes"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
