---
#
- name:  config_repo | config gitlab-ce repo
  yum_repository:
    file: "gitlab_gitlab-ce"
    name: "gitlab_gitlab-ce"
    description: "gitlab gitlab-ce repository"
    baseurl: "https://packages.gitlab.com/gitlab/gitlab-ce/el/{{ ansible_distribution_major_version }}/$basearch"
    gpgcheck: 1
    gpgkey: "https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
       https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey/gitlab-gitlab-ce-3D645A26AB9FBD22.pub.gpg"
    metadata_expire: '300'
    enabled: 1

- name: config_repo | config gitlab_gitlab-ce-source repo
  yum_repository:
    file: "gitlab_gitlab-ce"
    name: "gitlab_gitlab-ce-source"
    description: "gitlab gitlab-ce repository"
    baseurl: "https://packages.gitlab.com/gitlab/gitlab-ce/el/{{ ansible_distribution_major_version }}/SRPMS"
    gpgcheck: 1
    gpgkey: "https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
       https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey/gitlab-gitlab-ce-3D645A26AB9FBD22.pub.gpg"
    metadata_expire: '300'
    enabled: 1
