---
#

- name: Check if gitlab local file is already configured.
  state:
    path: "{{ soft_package_directory }}/{{ gitlab_package_name }}"
    checksum_algorithm: sha256
  register: gitlab_file_result

- name: install | jude soft directory
  file:
    path: "{{ soft_package_directory }}"
    state: directory
  when: not gitlab_file_result.stat.exists

- name: install | wget gitlab package
  get_url:
    url: "{{ gitlab_package_url }}"
    dest: "{{ soft_package_directory }}/{{ gitlab_package_name }}"
    checksum: "{{ gitlab_package_sha256 }}"
  when: not gitlab_file_result.stat.exists and gitlab_file_result.stat.checksum != {{ gitlab_package_sha256 }}

- name: install | install require soft
  yum:
    name: "{{ require_soft }}"
    state: installed

- name: install | install gitlab
  shell: "rpm -ivh {{ gitlab_package_name }}"
  args:
    chdir: {{ soft_package_directory }}
  when: {{ soft_package_directory }}/{{ gitlab_package_name }}